version: "2"

services:
  app:
    image: "${TAG_COMMIT}"
    container_name: kim-app
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=holyshitpassword
      - TELEGRAM_TOKEN
      - SECURITY_KEY
    ports:
      - "127.0.0.1:8000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: kim-postgres
    restart: always
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=holyshitpassword
      - POSTGRES_DB=kim
    expose:
      - "5432"

networks:
  default:
    name: kim-network
